krypton:
  server:
    port: 5000
    allow_origins: ["*"]
    allow_credentials: true
    allow_methods: ["GET", "POST", "OPTIONS"]
    allow_headers: ["*"]
    debug: true
  models:
    - name: langchain-example
      type: langchain
      callable: examples.langchain_example.app.chain
      endpoint: langchain-example
      description: Example LangChain model
      tags:
        - langchain
        - example
      options:
        debug: true