krypton:
  server:
    port: 5000
    allow_origins: ["*"]
    allow_credentials: true
    allow_methods: ["GET", "POST", "OPTIONS"]
    allow_headers: ["*"]
    debug: true
  models:
    - name: langchain-llama3.2-completion-example
      type: langchain
      description: llama3.2 completion example using langchain
      module_path: .
      callable: langchain_example.completion.chain
      endpoint: models/langchain/llama3.2/completion
      tags:
        - langchain
        - example
        - completion
    - name: langchain-llama3.2-chat-example
      type: langchain
      description: llama3.2 chat example using langchain
      module_path: .
      callable: langchain_example.chat.chain
      endpoint: models/langchain/llama3.2/chat
      tags:
        - langchain
        - example
        - chat
    - name: custom-model-example
      type: custom
      description: Custom model example
      module_path: .
      callable: custom.custom_model.CustomModelExample
      endpoint: models/custom/example
      tags:
        - custom
        - example
    - name: gpt2-model
      type: huggingface
      description: GPT-2 text generation model
      endpoint: models/gpt2/generate
      hf_model_name: "gpt2"
      hf_task: "generation"
      hf_generation_kwargs:
        max_length: 100
        temperature: 0.7
        top_p: 0.9
      tags:
        - huggingface
        - text-generation
    - name: t5-translator
      type: huggingface
      description: T5 translation model
      endpoint: models/t5/translate
      hf_model_name: "t5-small"
      hf_task: "seq2seq"
      hf_generation_kwargs:
        max_length: 50
      tags:
        - huggingface
        - translation